//! NNUE trainer: pure Rust, CPU-only backpropagation + Adam optimizer.
//!
//! Trains the 768 → 256×2 → 32 → 32 → 1 network using self-play data
//! generated by the `selfplay` command. Outputs a .nnue file compatible
//! with the inference code in `src/nnue/`.
//!
//! Usage: `cargo run --release -- train <data_file> [options]`

use crate::nnue::network::{FT_SIZE, L1_INPUT, L1_SIZE, L2_SIZE, QA, QB};
use crate::nnue::features::NUM_FEATURES;

const SIGMOID_SCALE: f32 = 400.0;

// ════════════════════════════════════════════════════════════════════════════
// Data structures
// ════════════════════════════════════════════════════════════════════════════

/// Training sample parsed from a ChessBoard record.
struct Sample {
    stm_features: Vec<usize>,
    opp_features: Vec<usize>,
    score: f32,
    result: f32,
}

/// f32 network weights for training.
#[derive(Clone)]
struct TrainNet {
    ft_weights: Vec<f32>,
    ft_biases: Vec<f32>,
    l1_weights: Vec<f32>,
    l1_biases: Vec<f32>,
    l2_weights: Vec<f32>,
    l2_biases: Vec<f32>,
    l3_weights: Vec<f32>,
    l3_bias: f32,
}

/// Gradient accumulator (same layout as TrainNet).
struct Gradients {
    ft_weights: Vec<f32>,
    ft_biases: Vec<f32>,
    l1_weights: Vec<f32>,
    l1_biases: Vec<f32>,
    l2_weights: Vec<f32>,
    l2_biases: Vec<f32>,
    l3_weights: Vec<f32>,
    l3_bias: f32,
}

/// All intermediate values needed for backpropagation.
struct ForwardState {
    stm_acc: Vec<f32>,
    opp_acc: Vec<f32>,
    l1_input: Vec<f32>,
    l1_pre: Vec<f32>,
    l1_out: Vec<f32>,
    l2_pre: Vec<f32>,
    l2_out: Vec<f32>,
    output: f32,
}

/// Adam optimizer state.
struct Adam {
    lr: f32,
    beta1: f32,
    beta2: f32,
    epsilon: f32,
    t: u32,
    m: TrainNet,
    v: TrainNet,
}

/// Training configuration.
struct TrainConfig {
    data_paths: Vec<String>,
    data_weights: Vec<f32>,
    output_path: String,
    resume_path: Option<String>,
    warmup_lr_factor: f32,
    warmup_epochs: usize,
    epochs: usize,
    batch_size: usize,
    lr: f32,
    wdl_weight: f32,
    save_rate: usize,
    num_threads: usize,
}

// ════════════════════════════════════════════════════════════════════════════
// PRNG (deterministic, no external crate)
// ════════════════════════════════════════════════════════════════════════════

struct Rng {
    state: u64,
}

impl Rng {
    fn new(seed: u64) -> Self {
        Rng { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 7;
        self.state ^= self.state << 17;
        self.state
    }

    fn next_f32(&mut self) -> f32 {
        (self.next_u64() >> 40) as f32 / (1u64 << 24) as f32
    }

    /// Box-Muller transform for Gaussian samples.
    fn next_gaussian(&mut self) -> f32 {
        let u1 = self.next_f32().max(1e-10);
        let u2 = self.next_f32();
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f32::consts::PI * u2).cos()
    }

    fn shuffle<T>(&mut self, data: &mut [T]) {
        for i in (1..data.len()).rev() {
            let j = (self.next_u64() as usize) % (i + 1);
            data.swap(i, j);
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Network initialization
// ════════════════════════════════════════════════════════════════════════════

impl TrainNet {
    fn zeros() -> Self {
        TrainNet {
            ft_weights: vec![0.0; NUM_FEATURES * FT_SIZE],
            ft_biases: vec![0.0; FT_SIZE],
            l1_weights: vec![0.0; L1_INPUT * L1_SIZE],
            l1_biases: vec![0.0; L1_SIZE],
            l2_weights: vec![0.0; L1_SIZE * L2_SIZE],
            l2_biases: vec![0.0; L2_SIZE],
            l3_weights: vec![0.0; L2_SIZE],
            l3_bias: 0.0,
        }
    }

    fn random_init(rng: &mut Rng) -> Self {
        let mut net = Self::zeros();

        // Feature transformer: ~30 active features, values should be in i16 range
        // He init: std = sqrt(2/fan_in) * scale
        let ft_std = (2.0 / 30.0_f32).sqrt() * 10.0;
        for w in &mut net.ft_weights {
            *w = rng.next_gaussian() * ft_std;
        }

        // L1: fan_in = 512, values should be in i8-ish range
        let l1_std = (2.0 / L1_INPUT as f32).sqrt() * 16.0;
        for w in &mut net.l1_weights {
            *w = rng.next_gaussian() * l1_std;
        }

        // L2: fan_in = 32
        let l2_std = (2.0 / L1_SIZE as f32).sqrt() * 16.0;
        for w in &mut net.l2_weights {
            *w = rng.next_gaussian() * l2_std;
        }

        // L3: fan_in = 32
        let l3_std = (2.0 / L2_SIZE as f32).sqrt() * 16.0;
        for w in &mut net.l3_weights {
            *w = rng.next_gaussian() * l3_std;
        }

        // Biases stay zero
        net
    }

    /// Load weights from an existing quantized Network (warm-start training).
    /// The quantization in `quantize()` is just round+clamp, so the inverse
    /// is a direct cast back to f32.
    fn from_network(net: &crate::nnue::network::Network) -> Self {
        TrainNet {
            ft_weights: net.ft_weights.iter().map(|&v| v as f32).collect(),
            ft_biases: net.ft_biases.iter().map(|&v| v as f32).collect(),
            l1_weights: net.l1_weights.iter().map(|&v| v as f32).collect(),
            l1_biases: net.l1_biases.iter().map(|&v| v as f32).collect(),
            l2_weights: net.l2_weights.iter().map(|&v| v as f32).collect(),
            l2_biases: net.l2_biases.iter().map(|&v| v as f32).collect(),
            l3_weights: net.l3_weights.iter().map(|&v| v as f32).collect(),
            l3_bias: net.l3_bias as f32,
        }
    }
}

impl Gradients {
    fn zeros() -> Self {
        Gradients {
            ft_weights: vec![0.0; NUM_FEATURES * FT_SIZE],
            ft_biases: vec![0.0; FT_SIZE],
            l1_weights: vec![0.0; L1_INPUT * L1_SIZE],
            l1_biases: vec![0.0; L1_SIZE],
            l2_weights: vec![0.0; L1_SIZE * L2_SIZE],
            l2_biases: vec![0.0; L2_SIZE],
            l3_weights: vec![0.0; L2_SIZE],
            l3_bias: 0.0,
        }
    }

    fn scale(&mut self, factor: f32) {
        for w in &mut self.ft_weights { *w *= factor; }
        for w in &mut self.ft_biases { *w *= factor; }
        for w in &mut self.l1_weights { *w *= factor; }
        for w in &mut self.l1_biases { *w *= factor; }
        for w in &mut self.l2_weights { *w *= factor; }
        for w in &mut self.l2_biases { *w *= factor; }
        for w in &mut self.l3_weights { *w *= factor; }
        self.l3_bias *= factor;
    }

    fn clear(&mut self) {
        self.ft_weights.fill(0.0);
        self.ft_biases.fill(0.0);
        self.l1_weights.fill(0.0);
        self.l1_biases.fill(0.0);
        self.l2_weights.fill(0.0);
        self.l2_biases.fill(0.0);
        self.l3_weights.fill(0.0);
        self.l3_bias = 0.0;
    }

    /// Accumulate another gradient into this one (for parallel batch reduction).
    fn add(&mut self, other: &Gradients) {
        for i in 0..self.ft_weights.len() { self.ft_weights[i] += other.ft_weights[i]; }
        for i in 0..self.ft_biases.len() { self.ft_biases[i] += other.ft_biases[i]; }
        for i in 0..self.l1_weights.len() { self.l1_weights[i] += other.l1_weights[i]; }
        for i in 0..self.l1_biases.len() { self.l1_biases[i] += other.l1_biases[i]; }
        for i in 0..self.l2_weights.len() { self.l2_weights[i] += other.l2_weights[i]; }
        for i in 0..self.l2_biases.len() { self.l2_biases[i] += other.l2_biases[i]; }
        for i in 0..self.l3_weights.len() { self.l3_weights[i] += other.l3_weights[i]; }
        self.l3_bias += other.l3_bias;
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Adam optimizer
// ════════════════════════════════════════════════════════════════════════════

impl Adam {
    fn new(lr: f32) -> Self {
        Adam {
            lr,
            beta1: 0.9,
            beta2: 0.999,
            epsilon: 1e-8,
            t: 0,
            m: TrainNet::zeros(),
            v: TrainNet::zeros(),
        }
    }

    fn step(&mut self, net: &mut TrainNet, grad: &Gradients) {
        self.t += 1;
        let bc1 = 1.0 - self.beta1.powi(self.t as i32);
        let bc2 = 1.0 - self.beta2.powi(self.t as i32);

        macro_rules! adam_update {
            ($param:expr, $grad:expr, $m:expr, $v:expr) => {
                for i in 0..$param.len() {
                    let g = $grad[i];
                    $m[i] = self.beta1 * $m[i] + (1.0 - self.beta1) * g;
                    $v[i] = self.beta2 * $v[i] + (1.0 - self.beta2) * g * g;
                    let m_hat = $m[i] / bc1;
                    let v_hat = $v[i] / bc2;
                    $param[i] -= self.lr * m_hat / (v_hat.sqrt() + self.epsilon);
                }
            };
        }

        adam_update!(net.ft_weights, grad.ft_weights, self.m.ft_weights, self.v.ft_weights);
        adam_update!(net.ft_biases, grad.ft_biases, self.m.ft_biases, self.v.ft_biases);
        adam_update!(net.l1_weights, grad.l1_weights, self.m.l1_weights, self.v.l1_weights);
        adam_update!(net.l1_biases, grad.l1_biases, self.m.l1_biases, self.v.l1_biases);
        adam_update!(net.l2_weights, grad.l2_weights, self.m.l2_weights, self.v.l2_weights);
        adam_update!(net.l2_biases, grad.l2_biases, self.m.l2_biases, self.v.l2_biases);
        adam_update!(net.l3_weights, grad.l3_weights, self.m.l3_weights, self.v.l3_weights);

        // Scalar bias
        let g = grad.l3_bias;
        self.m.l3_bias = self.beta1 * self.m.l3_bias + (1.0 - self.beta1) * g;
        self.v.l3_bias = self.beta2 * self.v.l3_bias + (1.0 - self.beta2) * g * g;
        let m_hat = self.m.l3_bias / bc1;
        let v_hat = self.v.l3_bias / bc2;
        net.l3_bias -= self.lr * m_hat / (v_hat.sqrt() + self.epsilon);
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Data loading
// ════════════════════════════════════════════════════════════════════════════

fn load_data(path: &str) -> Vec<Sample> {
    let data = std::fs::read(path)
        .unwrap_or_else(|e| panic!("Failed to read data file '{path}': {e}"));

    if data.len() % 32 != 0 {
        panic!("Data file size {} is not a multiple of 32 bytes", data.len());
    }

    let num_records = data.len() / 32;
    let mut samples = Vec::with_capacity(num_records);

    for i in 0..num_records {
        let record = &data[i * 32..(i + 1) * 32];
        if let Some(sample) = parse_record(record) {
            samples.push(sample);
        }
    }

    samples
}

/// Load multiple files and combine according to weights.
/// Weights are normalized; each file contributes positions proportional to its weight,
/// scaled so total = sum of all loaded positions (no truncation when possible).
fn load_data_multi(paths: &[String], weights: &[f32], rng: &mut Rng) -> Vec<Sample> {
    assert_eq!(paths.len(), weights.len(), "data paths and weights must match");

    let mut per_file: Vec<Vec<Sample>> = Vec::with_capacity(paths.len());
    for path in paths {
        eprintln!("  Loading {path}...");
        per_file.push(load_data(path));
    }

    let total_weight: f32 = weights.iter().sum();
    let total_loaded: usize = per_file.iter().map(|v| v.len()).sum();

    // Total target = total_loaded; each file gets proportional share.
    // For files with weight that demands more than they have, oversample (sample with replacement).
    // For files demanding less, undersample (random subset without replacement).
    let mut combined = Vec::with_capacity(total_loaded);
    for (i, samples) in per_file.iter_mut().enumerate() {
        let target = ((weights[i] / total_weight) * total_loaded as f32) as usize;
        let available = samples.len();
        if available == 0 {
            continue;
        }

        if target <= available {
            // Random subset without replacement (Fisher-Yates partial shuffle, take first `target`)
            for j in 0..target {
                let pick = j + (rng.next_u64() as usize) % (available - j);
                samples.swap(j, pick);
            }
            combined.extend(samples.drain(0..target));
        } else {
            // Take all + oversample with replacement for the rest
            combined.append(samples);
            let extra = target - available;
            for _ in 0..extra {
                let idx = (rng.next_u64() as usize) % combined.len();
                let s = &combined[idx];
                combined.push(Sample {
                    stm_features: s.stm_features.clone(),
                    opp_features: s.opp_features.clone(),
                    score: s.score,
                    result: s.result,
                });
            }
        }

        let pct = 100.0 * weights[i] / total_weight;
        eprintln!("    {} → {} positions ({:.1}% of mix)", paths[i], target, pct);
    }

    combined
}

fn parse_record(data: &[u8]) -> Option<Sample> {
    let occ = u64::from_le_bytes([
        data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7],
    ]);
    let pcs = &data[8..24];
    let score = i16::from_le_bytes([data[24], data[25]]) as f32;
    let result_byte = data[26];
    let result = result_byte as f32 / 2.0;

    // Filter: skip extreme evals
    if score.abs() > 10000.0 {
        return None;
    }

    let mut stm_features = Vec::with_capacity(32);
    let mut opp_features = Vec::with_capacity(32);
    let mut remaining = occ;
    let mut piece_idx = 0usize;

    while remaining != 0 {
        let sq = remaining.trailing_zeros() as usize;
        remaining &= remaining - 1;

        let byte_idx = piece_idx / 2;
        let shift = 4 * (piece_idx & 1);
        let nibble = (pcs[byte_idx] >> shift) & 0x0F;
        piece_idx += 1;

        let piece_type = (nibble & 0x07) as usize;
        let is_opponent = (nibble & 0x08) != 0;

        // STM perspective (STM = color 0 in the record)
        let stm_color = if is_opponent { 1 } else { 0 };
        let stm_idx = stm_color * 384 + piece_type * 64 + sq;

        // Opponent perspective: flip color and square
        let opp_color = if is_opponent { 0 } else { 1 };
        let opp_sq = sq ^ 56;
        let opp_idx = opp_color * 384 + piece_type * 64 + opp_sq;

        if stm_idx < NUM_FEATURES && opp_idx < NUM_FEATURES {
            stm_features.push(stm_idx);
            opp_features.push(opp_idx);
        }
    }

    Some(Sample { stm_features, opp_features, score, result })
}

// ════════════════════════════════════════════════════════════════════════════
// Forward pass (f32, mirrors quantized inference)
// ════════════════════════════════════════════════════════════════════════════

fn forward(net: &TrainNet, sample: &Sample) -> ForwardState {
    let qa = QA as f32;
    let qb = QB as f32;

    // Feature transformer (sparse)
    let mut stm_acc = net.ft_biases.clone();
    for &idx in &sample.stm_features {
        let offset = idx * FT_SIZE;
        for j in 0..FT_SIZE {
            stm_acc[j] += net.ft_weights[offset + j];
        }
    }

    let mut opp_acc = net.ft_biases.clone();
    for &idx in &sample.opp_features {
        let offset = idx * FT_SIZE;
        for j in 0..FT_SIZE {
            opp_acc[j] += net.ft_weights[offset + j];
        }
    }

    // SCReLU: clamp(x, 0, QA)²
    let mut l1_input = vec![0.0f32; L1_INPUT];
    for i in 0..FT_SIZE {
        let c = stm_acc[i].clamp(0.0, qa);
        l1_input[i] = c * c;
    }
    for i in 0..FT_SIZE {
        let c = opp_acc[i].clamp(0.0, qa);
        l1_input[FT_SIZE + i] = c * c;
    }

    // Layer 1: (bias + matmul) / QA, then CReLU
    let mut l1_pre = vec![0.0f32; L1_SIZE];
    for j in 0..L1_SIZE {
        let mut sum = net.l1_biases[j];
        for i in 0..L1_INPUT {
            sum += l1_input[i] * net.l1_weights[i * L1_SIZE + j];
        }
        l1_pre[j] = sum / qa;
    }
    let mut l1_out = vec![0.0f32; L1_SIZE];
    for j in 0..L1_SIZE {
        l1_out[j] = l1_pre[j].clamp(0.0, qb);
    }

    // Layer 2: bias + matmul, then CReLU
    let mut l2_pre = vec![0.0f32; L2_SIZE];
    for j in 0..L2_SIZE {
        let mut sum = net.l2_biases[j];
        for i in 0..L1_SIZE {
            sum += l1_out[i] * net.l2_weights[i * L2_SIZE + j];
        }
        l2_pre[j] = sum;
    }
    let mut l2_out = vec![0.0f32; L2_SIZE];
    for j in 0..L2_SIZE {
        l2_out[j] = l2_pre[j].clamp(0.0, qb);
    }

    // Output: (bias + dot) / QB
    let mut output = net.l3_bias;
    for j in 0..L2_SIZE {
        output += l2_out[j] * net.l3_weights[j];
    }
    output /= qb;

    ForwardState { stm_acc, opp_acc, l1_input, l1_pre, l1_out, l2_pre, l2_out, output }
}

// ════════════════════════════════════════════════════════════════════════════
// Loss function
// ════════════════════════════════════════════════════════════════════════════

fn sigmoid(x: f32) -> f32 {
    1.0 / (1.0 + (-x / SIGMOID_SCALE).exp())
}

fn loss_and_gradient(predicted_cp: f32, score_cp: f32, result: f32, wdl_weight: f32) -> (f32, f32) {
    let pred_sig = sigmoid(predicted_cp);
    let target_sig = sigmoid(score_cp);
    let target = wdl_weight * result + (1.0 - wdl_weight) * target_sig;

    let loss = (target - pred_sig).powi(2);

    // d(loss)/d(predicted_cp)
    let d_sigmoid = pred_sig * (1.0 - pred_sig) / SIGMOID_SCALE;
    let d_loss = 2.0 * (pred_sig - target) * d_sigmoid;

    (loss, d_loss)
}

// ════════════════════════════════════════════════════════════════════════════
// Backward pass
// ════════════════════════════════════════════════════════════════════════════

fn backward(
    net: &TrainNet,
    sample: &Sample,
    fwd: &ForwardState,
    d_loss: f32,
    grad: &mut Gradients,
) {
    let qa = QA as f32;
    let qb = QB as f32;

    // ── Output layer ───────────────────────────────────────────────────
    // output = (l3_bias + sum(l2_out * l3_weights)) / QB
    let d_output = d_loss / qb;

    grad.l3_bias += d_output;
    let mut d_l2_out = vec![0.0f32; L2_SIZE];
    for j in 0..L2_SIZE {
        grad.l3_weights[j] += d_output * fwd.l2_out[j];
        d_l2_out[j] = d_output * net.l3_weights[j];
    }

    // ── Layer 2 CReLU gradient ─────────────────────────────────────────
    let mut d_l2_pre = vec![0.0f32; L2_SIZE];
    for j in 0..L2_SIZE {
        d_l2_pre[j] = if fwd.l2_pre[j] > 0.0 && fwd.l2_pre[j] < qb {
            d_l2_out[j]
        } else {
            0.0
        };
    }

    // ── Layer 2 linear gradient ────────────────────────────────────────
    let mut d_l1_out = vec![0.0f32; L1_SIZE];
    for j in 0..L2_SIZE {
        grad.l2_biases[j] += d_l2_pre[j];
        for i in 0..L1_SIZE {
            grad.l2_weights[i * L2_SIZE + j] += d_l2_pre[j] * fwd.l1_out[i];
            d_l1_out[i] += d_l2_pre[j] * net.l2_weights[i * L2_SIZE + j];
        }
    }

    // ── Layer 1 CReLU gradient ─────────────────────────────────────────
    let mut d_l1_pre = vec![0.0f32; L1_SIZE];
    for j in 0..L1_SIZE {
        d_l1_pre[j] = if fwd.l1_pre[j] > 0.0 && fwd.l1_pre[j] < qb {
            d_l1_out[j]
        } else {
            0.0
        };
    }

    // ── Layer 1 linear gradient ────────────────────────────────────────
    // l1_pre[j] = (l1_biases[j] + sum(l1_input * l1_weights)) / QA
    let mut d_l1_input = vec![0.0f32; L1_INPUT];
    for j in 0..L1_SIZE {
        let d = d_l1_pre[j] / qa;
        grad.l1_biases[j] += d;
        for i in 0..L1_INPUT {
            grad.l1_weights[i * L1_SIZE + j] += d * fwd.l1_input[i];
            d_l1_input[i] += d * net.l1_weights[i * L1_SIZE + j];
        }
    }

    // ── SCReLU gradient ────────────────────────────────────────────────
    // l1_input[i] = clamp(acc[i], 0, QA)²
    // d/dx = 2 * clamp(x, 0, QA) when 0 < x < QA
    let mut d_stm_acc = vec![0.0f32; FT_SIZE];
    let mut d_opp_acc = vec![0.0f32; FT_SIZE];
    for i in 0..FT_SIZE {
        let x = fwd.stm_acc[i];
        if x > 0.0 && x < qa {
            d_stm_acc[i] = d_l1_input[i] * 2.0 * x;
        }
    }
    for i in 0..FT_SIZE {
        let x = fwd.opp_acc[i];
        if x > 0.0 && x < qa {
            d_opp_acc[i] = d_l1_input[FT_SIZE + i] * 2.0 * x;
        }
    }

    // ── Feature transformer gradient (sparse) ──────────────────────────
    // Bias is shared between both perspectives
    for j in 0..FT_SIZE {
        grad.ft_biases[j] += d_stm_acc[j] + d_opp_acc[j];
    }

    // Only update weight rows for active features
    for &idx in &sample.stm_features {
        let offset = idx * FT_SIZE;
        for j in 0..FT_SIZE {
            grad.ft_weights[offset + j] += d_stm_acc[j];
        }
    }
    for &idx in &sample.opp_features {
        let offset = idx * FT_SIZE;
        for j in 0..FT_SIZE {
            grad.ft_weights[offset + j] += d_opp_acc[j];
        }
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Quantization
// ════════════════════════════════════════════════════════════════════════════

fn quantize(net: &TrainNet) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(412_000);

    // FT biases [FT_SIZE] as i16
    for j in 0..FT_SIZE {
        let v = net.ft_biases[j].round().clamp(-32768.0, 32767.0) as i16;
        bytes.extend_from_slice(&v.to_le_bytes());
    }

    // FT weights [NUM_FEATURES * FT_SIZE] as i16
    for i in 0..(NUM_FEATURES * FT_SIZE) {
        let v = net.ft_weights[i].round().clamp(-32768.0, 32767.0) as i16;
        bytes.extend_from_slice(&v.to_le_bytes());
    }

    // L1 biases [L1_SIZE] as i32
    for j in 0..L1_SIZE {
        let v = net.l1_biases[j].round() as i32;
        bytes.extend_from_slice(&v.to_le_bytes());
    }

    // L1 weights [L1_INPUT * L1_SIZE] as i8
    for i in 0..(L1_INPUT * L1_SIZE) {
        let v = net.l1_weights[i].round().clamp(-128.0, 127.0) as i8;
        bytes.push(v as u8);
    }

    // L2 biases [L2_SIZE] as i32
    for j in 0..L2_SIZE {
        let v = net.l2_biases[j].round() as i32;
        bytes.extend_from_slice(&v.to_le_bytes());
    }

    // L2 weights [L1_SIZE * L2_SIZE] as i8
    for i in 0..(L1_SIZE * L2_SIZE) {
        let v = net.l2_weights[i].round().clamp(-128.0, 127.0) as i8;
        bytes.push(v as u8);
    }

    // L3 bias as i32
    let v = net.l3_bias.round() as i32;
    bytes.extend_from_slice(&v.to_le_bytes());

    // L3 weights [L2_SIZE] as i8
    for j in 0..L2_SIZE {
        let v = net.l3_weights[j].round().clamp(-128.0, 127.0) as i8;
        bytes.push(v as u8);
    }

    bytes
}

// ════════════════════════════════════════════════════════════════════════════
// Training loop
// ════════════════════════════════════════════════════════════════════════════

fn train(config: &TrainConfig) {
    let mut rng = Rng::new(0xDEAD_CAFE_1234);

    eprintln!("Loading data...");
    let mut samples = if config.data_paths.len() == 1 {
        load_data(&config.data_paths[0])
    } else {
        load_data_multi(&config.data_paths, &config.data_weights, &mut rng)
    };
    eprintln!("Loaded {} total positions.", samples.len());

    if samples.is_empty() {
        eprintln!("No training data. Aborting.");
        return;
    }

    // Initialize network: resume from .nnue or random init
    let mut net = if let Some(resume_path) = &config.resume_path {
        eprintln!("Resuming training from existing net: {resume_path}");
        let bytes = std::fs::read(resume_path)
            .unwrap_or_else(|e| panic!("Failed to read resume net '{resume_path}': {e}"));
        let loaded = crate::nnue::network::Network::from_bytes(&bytes)
            .unwrap_or_else(|e| panic!("Failed to parse resume net: {e}"));
        TrainNet::from_network(&loaded)
    } else {
        eprintln!("Initializing fresh random network.");
        TrainNet::random_init(&mut rng)
    };

    // Use reduced LR for first warmup_epochs when resuming (preserves learned features)
    let initial_lr = if config.resume_path.is_some() && config.warmup_epochs > 0 {
        config.lr * config.warmup_lr_factor
    } else {
        config.lr
    };
    let mut adam = Adam::new(initial_lr);

    let lr_drop_1 = config.epochs * 3 / 4;
    let lr_drop_2 = config.epochs * 9 / 10;

    eprintln!("Training: {} epochs, batch_size={}, lr={}, wdl={:.2}, threads={}, save every {} epochs",
        config.epochs, config.batch_size, config.lr, config.wdl_weight, config.num_threads, config.save_rate);
    eprintln!("LR drops at epochs {} and {}", lr_drop_1, lr_drop_2);
    if config.resume_path.is_some() && config.warmup_epochs > 0 {
        eprintln!("Warm-start: LR x{:.2} for first {} epochs, then ramp to {}",
            config.warmup_lr_factor, config.warmup_epochs, config.lr);
    }

    let num_threads = config.num_threads.max(1);

    for epoch in 1..=config.epochs {
        // Warm-up: ramp LR from warmup_lr_factor*lr back to full lr after warmup_epochs
        if config.resume_path.is_some()
            && config.warmup_epochs > 0
            && epoch == config.warmup_epochs + 1
        {
            adam.lr = config.lr;
            eprintln!("  Warm-up complete; LR restored to {:.6}", adam.lr);
        }

        rng.shuffle(&mut samples);

        let mut epoch_loss = 0.0f64;
        let mut epoch_count = 0u64;
        let mut grad = Gradients::zeros();

        for batch_start in (0..samples.len()).step_by(config.batch_size) {
            let batch_end = (batch_start + config.batch_size).min(samples.len());
            let batch_len = batch_end - batch_start;
            let batch = &samples[batch_start..batch_end];

            grad.clear();

            // Parallel forward+backward across threads, each with local Gradients
            let net_ref = &net;
            let wdl = config.wdl_weight;
            let chunk_size = batch_len.div_ceil(num_threads);

            let results: Vec<(Gradients, f64)> = std::thread::scope(|scope| {
                let mut handles = Vec::with_capacity(num_threads);
                for chunk in batch.chunks(chunk_size) {
                    handles.push(scope.spawn(move || {
                        let mut local_grad = Gradients::zeros();
                        let mut local_loss = 0.0f64;
                        for sample in chunk {
                            let fwd = forward(net_ref, sample);
                            let (loss, d_loss) = loss_and_gradient(
                                fwd.output, sample.score, sample.result, wdl,
                            );
                            backward(net_ref, sample, &fwd, d_loss, &mut local_grad);
                            local_loss += loss as f64;
                        }
                        (local_grad, local_loss)
                    }));
                }
                handles.into_iter().map(|h| h.join().unwrap()).collect()
            });

            // Reduce per-thread gradients into the main one
            for (g, loss) in results {
                grad.add(&g);
                epoch_loss += loss;
            }
            epoch_count += batch_len as u64;

            grad.scale(1.0 / batch_len as f32);
            adam.step(&mut net, &grad);
        }

        let avg_loss = epoch_loss / epoch_count as f64;
        eprintln!("Epoch {epoch}/{}: loss = {avg_loss:.8}", config.epochs);

        // Checkpoint save
        if config.save_rate > 0 && epoch % config.save_rate == 0 && epoch < config.epochs {
            let checkpoint_path = format!(
                "{}-epoch{}.nnue",
                config.output_path.trim_end_matches(".nnue"),
                epoch
            );
            let bytes = quantize(&net);
            if let Err(e) = std::fs::write(&checkpoint_path, &bytes) {
                eprintln!("  WARNING: failed to save checkpoint: {e}");
            } else {
                eprintln!("  Checkpoint saved: {checkpoint_path}");
            }
        }

        // LR schedule
        if epoch == lr_drop_1 || epoch == lr_drop_2 {
            adam.lr *= 0.3;
            eprintln!("  LR dropped to {:.6}", adam.lr);
        }
    }

    // Final save
    eprintln!("Quantizing and saving to '{}'...", config.output_path);
    let bytes = quantize(&net);
    std::fs::write(&config.output_path, &bytes)
        .unwrap_or_else(|e| panic!("Failed to write '{}': {e}", config.output_path));
    eprintln!("Done! Saved {} bytes ({} KB).", bytes.len(), bytes.len() / 1024);

    // Verify the output is loadable
    match crate::nnue::network::Network::from_bytes(&bytes) {
        Ok(_) => eprintln!("Verification: net file loads successfully."),
        Err(e) => eprintln!("WARNING: net file failed to load: {e}"),
    }
}

// ════════════════════════════════════════════════════════════════════════════
// CLI entry point
// ════════════════════════════════════════════════════════════════════════════

pub fn run_training(first_data_path: &str, args: &[String]) {
    let default_threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(1);

    let mut config = TrainConfig {
        data_paths: vec![first_data_path.to_string()],
        data_weights: Vec::new(),
        output_path: "focalors.nnue".to_string(),
        resume_path: None,
        warmup_lr_factor: 0.3,
        warmup_epochs: 3,
        epochs: 20,
        batch_size: 16384,
        lr: 0.001,
        wdl_weight: 0.5,
        save_rate: 5,
        num_threads: default_threads,
    };

    // Parse optional args
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--data" => {
                if let Some(p) = args.get(i + 1) {
                    config.data_paths.push(p.clone());
                }
                i += 2;
            }
            "--mix" => {
                if let Some(s) = args.get(i + 1) {
                    config.data_weights = s.split(',')
                        .filter_map(|p| p.parse::<f32>().ok())
                        .collect();
                }
                i += 2;
            }
            "--resume" => {
                config.resume_path = args.get(i + 1).cloned();
                i += 2;
            }
            "--warmup-lr-factor" => {
                config.warmup_lr_factor = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(0.3);
                i += 2;
            }
            "--warmup-epochs" => {
                config.warmup_epochs = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(3);
                i += 2;
            }
            "--epochs" => {
                config.epochs = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(20);
                i += 2;
            }
            "--batch-size" => {
                config.batch_size = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(16384);
                i += 2;
            }
            "--lr" => {
                config.lr = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(0.001);
                i += 2;
            }
            "--wdl" => {
                config.wdl_weight = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(0.5);
                i += 2;
            }
            "--output" => {
                config.output_path = args.get(i + 1).cloned().unwrap_or("focalors.nnue".into());
                i += 2;
            }
            "--save-rate" => {
                config.save_rate = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(5);
                i += 2;
            }
            "--threads" => {
                config.num_threads = args.get(i + 1).and_then(|s| s.parse().ok()).unwrap_or(default_threads);
                i += 2;
            }
            _ => { i += 1; }
        }
    }

    // Default mixing weights to equal if not specified or count mismatch
    if config.data_weights.len() != config.data_paths.len() {
        if !config.data_weights.is_empty() {
            eprintln!("Warning: --mix has {} weights but {} --data files; using equal weights",
                config.data_weights.len(), config.data_paths.len());
        }
        config.data_weights = vec![1.0; config.data_paths.len()];
    }

    train(&config);
}

// ════════════════════════════════════════════════════════════════════════════
// Tests
// ════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sigmoid_at_zero_is_half() {
        let s = sigmoid(0.0);
        assert!((s - 0.5).abs() < 0.001);
    }

    #[test]
    fn quantize_roundtrip() {
        let mut rng = Rng::new(12345);
        let net = TrainNet::random_init(&mut rng);
        let bytes = quantize(&net);
        let loaded = crate::nnue::network::Network::from_bytes(&bytes);
        assert!(loaded.is_ok(), "Quantized net should be loadable");
    }

    #[test]
    fn forward_produces_finite_output() {
        let mut rng = Rng::new(42);
        let net = TrainNet::random_init(&mut rng);
        let sample = Sample {
            stm_features: vec![0, 64, 128, 192, 256, 320],
            opp_features: vec![384, 448, 512, 576, 640, 704],
            score: 50.0,
            result: 0.5,
        };
        let fwd = forward(&net, &sample);
        assert!(fwd.output.is_finite(), "Output should be finite, got {}", fwd.output);
    }

    #[test]
    fn gradient_check_output_layer() {
        // Numerical gradient check for a few output layer parameters
        let mut rng = Rng::new(99);
        let net = TrainNet::random_init(&mut rng);
        let sample = Sample {
            stm_features: vec![10, 74, 200, 300, 400, 500],
            opp_features: vec![390, 450, 520, 580, 650, 710],
            score: 100.0,
            result: 1.0,
        };

        let eps = 1e-3;

        // Check l3_weights[0]
        let mut net_plus = net.clone();
        let mut net_minus = net.clone();
        net_plus.l3_weights[0] += eps;
        net_minus.l3_weights[0] -= eps;

        let fwd_plus = forward(&net_plus, &sample);
        let fwd_minus = forward(&net_minus, &sample);
        let (loss_plus, _) = loss_and_gradient(fwd_plus.output, sample.score, sample.result, 0.5);
        let (loss_minus, _) = loss_and_gradient(fwd_minus.output, sample.score, sample.result, 0.5);
        let numerical_grad = (loss_plus - loss_minus) / (2.0 * eps);

        // Analytical gradient
        let fwd = forward(&net, &sample);
        let (_, d_loss) = loss_and_gradient(fwd.output, sample.score, sample.result, 0.5);
        let mut grad = Gradients::zeros();
        backward(&net, &sample, &fwd, d_loss, &mut grad);
        let analytical_grad = grad.l3_weights[0];

        let rel_error = if numerical_grad.abs() > 1e-7 {
            ((analytical_grad - numerical_grad) / numerical_grad).abs()
        } else {
            (analytical_grad - numerical_grad).abs()
        };

        assert!(
            rel_error < 0.01,
            "Gradient check failed: numerical={numerical_grad:.6}, analytical={analytical_grad:.6}, rel_error={rel_error:.6}"
        );
    }

    #[test]
    fn gradient_check_ft_weight() {
        let mut rng = Rng::new(77);
        let net = TrainNet::random_init(&mut rng);
        let sample = Sample {
            stm_features: vec![10, 74, 200],
            opp_features: vec![390, 450, 520],
            score: -50.0,
            result: 0.0,
        };

        let eps = 1e-3;
        // Check ft_weights for an active feature (index 10, neuron 5)
        let param_idx = 10 * FT_SIZE + 5;

        let mut net_plus = net.clone();
        let mut net_minus = net.clone();
        net_plus.ft_weights[param_idx] += eps;
        net_minus.ft_weights[param_idx] -= eps;

        let fwd_plus = forward(&net_plus, &sample);
        let fwd_minus = forward(&net_minus, &sample);
        let (loss_plus, _) = loss_and_gradient(fwd_plus.output, sample.score, sample.result, 0.5);
        let (loss_minus, _) = loss_and_gradient(fwd_minus.output, sample.score, sample.result, 0.5);
        let numerical_grad = (loss_plus - loss_minus) / (2.0 * eps);

        let fwd = forward(&net, &sample);
        let (_, d_loss) = loss_and_gradient(fwd.output, sample.score, sample.result, 0.5);
        let mut grad = Gradients::zeros();
        backward(&net, &sample, &fwd, d_loss, &mut grad);
        let analytical_grad = grad.ft_weights[param_idx];

        let rel_error = if numerical_grad.abs() > 1e-7 {
            ((analytical_grad - numerical_grad) / numerical_grad).abs()
        } else {
            (analytical_grad - numerical_grad).abs()
        };

        assert!(
            rel_error < 0.01,
            "FT gradient check failed: numerical={numerical_grad:.6}, analytical={analytical_grad:.6}, rel_error={rel_error:.6}"
        );
    }

    #[test]
    fn resume_from_nnue_roundtrip() {
        // Train a tiny network briefly, quantize it to a Network,
        // load back via from_network(), and verify forward output matches
        // (within rounding tolerance — quantize discards fractional bits).
        let mut rng = Rng::new(7777);
        let net_orig = TrainNet::random_init(&mut rng);

        // Quantize to Network bytes
        let bytes = quantize(&net_orig);
        let loaded_network = crate::nnue::network::Network::from_bytes(&bytes)
            .expect("quantized net should load");

        // Load back into TrainNet
        let net_resumed = TrainNet::from_network(&loaded_network);

        // Verify a forward pass on a random sample produces the same result
        // (within rounding error — quantize() rounds f32 to integer)
        let sample = Sample {
            stm_features: vec![10, 64, 200, 300, 400, 500],
            opp_features: vec![390, 450, 520, 580, 650, 710],
            score: 0.0,
            result: 0.5,
        };

        let fwd_orig = forward(&net_orig, &sample);
        let fwd_resumed = forward(&net_resumed, &sample);

        // The outputs should be very close (rounding to integer adds at most
        // ~0.5 per parameter, accumulated across the network). Allow generous tolerance.
        let diff = (fwd_orig.output - fwd_resumed.output).abs();
        assert!(
            diff < 100.0,
            "Resume roundtrip diverged too much: orig={} resumed={} diff={}",
            fwd_orig.output, fwd_resumed.output, diff
        );
    }

    #[test]
    fn from_network_preserves_dimensions() {
        let mut rng = Rng::new(1234);
        let net = TrainNet::random_init(&mut rng);
        let bytes = quantize(&net);
        let loaded = crate::nnue::network::Network::from_bytes(&bytes).unwrap();
        let resumed = TrainNet::from_network(&loaded);

        assert_eq!(resumed.ft_weights.len(), net.ft_weights.len());
        assert_eq!(resumed.ft_biases.len(), net.ft_biases.len());
        assert_eq!(resumed.l1_weights.len(), net.l1_weights.len());
        assert_eq!(resumed.l1_biases.len(), net.l1_biases.len());
        assert_eq!(resumed.l2_weights.len(), net.l2_weights.len());
        assert_eq!(resumed.l2_biases.len(), net.l2_biases.len());
        assert_eq!(resumed.l3_weights.len(), net.l3_weights.len());
    }

    #[test]
    fn loss_decreases_after_training_steps() {
        let mut rng = Rng::new(555);
        let mut net = TrainNet::random_init(&mut rng);
        let mut adam = Adam::new(0.001);

        // Create some fake samples
        let samples: Vec<Sample> = (0..100).map(|i| {
            Sample {
                stm_features: vec![i % 768, (i * 7 + 1) % 768, (i * 13 + 2) % 768],
                opp_features: vec![(i + 384) % 768, (i * 7 + 385) % 768, (i * 13 + 386) % 768],
                score: (i as f32 - 50.0) * 2.0,
                result: if i < 33 { 0.0 } else if i < 66 { 0.5 } else { 1.0 },
            }
        }).collect();

        // Compute initial loss
        let initial_loss: f64 = samples.iter().map(|s| {
            let fwd = forward(&net, s);
            let (loss, _) = loss_and_gradient(fwd.output, s.score, s.result, 0.5);
            loss as f64
        }).sum::<f64>() / samples.len() as f64;

        // Train for 50 steps
        let mut grad = Gradients::zeros();
        for _ in 0..50 {
            grad.clear();
            for s in &samples {
                let fwd = forward(&net, s);
                let (_, d_loss) = loss_and_gradient(fwd.output, s.score, s.result, 0.5);
                backward(&net, s, &fwd, d_loss, &mut grad);
            }
            grad.scale(1.0 / samples.len() as f32);
            adam.step(&mut net, &grad);
        }

        // Compute final loss
        let final_loss: f64 = samples.iter().map(|s| {
            let fwd = forward(&net, s);
            let (loss, _) = loss_and_gradient(fwd.output, s.score, s.result, 0.5);
            loss as f64
        }).sum::<f64>() / samples.len() as f64;

        assert!(
            final_loss < initial_loss,
            "Loss should decrease: initial={initial_loss:.6}, final={final_loss:.6}"
        );
    }
}
